### ISSUE TITLE
Thanks a lot ! I'd like to ask you one last thing 

### ISSUE THREAD

**Issue by dannpr** [Sajjon/K1#40]
Thanks a lot ! I'm using K1 and everything seems to work well, thanks ! 
Lasts questions, I hope I can make sense : 
1. I see that even if I'm doing `let privateKey = K1.ECDSA.PrivateKey() ` I cannot have access to the private key of the key pair, right ? 
2. About secure enclave, I can first authenticate the user with faceID by using secure enclave and then use your package to create a keypair on the K1 curve , verify and sign data right ? And store on Keychain the public key. 

thanks again for your responce

_Originally posted by @dannpr in https://github.com/Sajjon/K1/issues/39#issuecomment-1622198770_

**Comment by Sajjon** [comment]
let privateKey = K1.ECDSA.PrivateKey()

_IS_ the private key. "Keypair" is a superficial thing, it means PrivateKey and PublicKey. From the PrivateKey you can get the public key.

You probably wanna store the PrivateKey, not only the PublicKey in Keychain right? Depends on your application... but those questions are not related to this package.

Check the documentation to see how you can serialize the PrivateKey for storage in Keychain.
